title: William Kingsley
author: William Kingsley
avatar: profile.jpg
description: A professional website for showcasing my projects and work experience.
email: williamikingsley@outlook.com
url: https://williamkingsley.com
githuburl: https://github.com/data-programmer/data-programmer.github.io

meta:
  lang: "en-US"

nav:
  - {name: "Home", url: "/"}
  - {name: "Skills", url: "../#skills" }
  - {name: "Projects", url: "../#projects" }
  - {name: "Work Experience", url: "../#work" }
  - {name: "Education", url: "../#education"}
  - {name: "News", url: "/news.html"}
  - {name: "Contact", url: "/contact.html" }

docs:
  - {name: "Resume", url: "/assets/resume/resume.pdf"}

social:
  - {icon: 'bi-envelope', type: 'bi', link: 'mailto:williamikingsley@outlook.com'}
  - {icon: 'bi-linkedin', type: 'bi', link: 'www.linkedin.com/in/williamkingsley'}
  - {icon: 'bi-github', type: 'bi', link: 'https://github.com/data-programmer'}

google-id: ''